In [23]:
# Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [3]:
# Upload Dataset
df = pd.read_csv('Record.csv')
df

,ID,Age,Gender,Grade,Result
0,1,18.0,Other,High School,Good
1,2,18.0,Other,High School,Good
2,3,22.0,Male,High School,Good
3,4,17.0,Other,High School,Poor
4,5,NaN,Other,High School,Good
...,...,...,...,...,...
4995,4996,20.0,Other,Undergraduate,Good
4996,4997,24.0,Male,High School,Poor
4997,4998,22.0,Male,Undergraduate,Good
4998,4999,17.0,Male,Undergraduate,Good


In [4]:
# Remove the column which is not required
df.drop(columns = ['ID'],inplace = True)
df.head()

,Age,Gender,Grade,Result
0,18.0,Other,High School,Good
1,18.0,Other,High School,Good
2,22.0,Male,High School,Good
3,17.0,Other,High School,Poor
4,NaN,Other,High School,Good


In [5]:
# Train and split dataset
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Result']), df['Result'], test_size=0.2, random_state=42)

In [6]:
X_train.head()

,Age,Gender,Grade
4227,23.0,Female,High School
4676,23.0,Other,High School
800,18.0,Other,High School
3671,20.0,Male,High School
4193,17.0,Other,High School


In [7]:
X_train.shape

(4000, 3)

In [8]:
y_train

4227    Average
4676    Average
800        Poor
3671       Good
4193       Poor
         ...   
4426       Poor
466     Average
3092       Poor
3772       Poor
860        Poor
Name: Result, Length: 4000, dtype: object

In [9]:
y_train.shape

(4000,)

In [10]:
# See if there is any missing data
df.isnull().sum()

Age       6
Gender    0
Grade     0
Result    0
dtype: int64

In [11]:
# Apply smple imputer to Age to compensate missing value
si_Age = SimpleImputer()
X_train_Age = si_Age.fit_transform(X_train[['Age']])
X_test_Age = si_Age.transform(X_test[['Age']])
X_train_Age

array([[23.],
       [23.],
       [18.],
       ...,
       [17.],
       [21.],
       [18.]], shape=(4000, 1))

In [12]:
X_test_Age

array([[21.       ],
       [22.       ],
       [23.       ],
       [20.       ],
       [19.       ],
       [16.       ],
       [18.       ],
       [22.       ],
       [17.       ],
       [20.       ],
       [19.       ],
       [19.       ],
       [23.       ],
       [20.       ],
       [23.       ],
       [24.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [24.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [23.       ],
       [18.       ],
       [22.       ],
       [16.       ],
       [21.       ],
       [19.       ],
       [18.       ],
       [20.       ],
       [25.       ],
       [24.       ],
       [23.       ],
       [19.       ],
       [16.       ],
       [16.       ],
       [17.       ],
       [19.       ],
       [23.       ],
       [16.       ],
       [22.       ],
       [23.       ],
       [17.       ],
       [19.       ],
       [24.       ],
       [24.       ],
       [19.  

In [13]:
# Gender is a nominal category so apply OneHot Encoder
ohe_Gender = OneHotEncoder (sparse_output = False,handle_unknown ='ignore')
X_train_Gender = ohe_Gender.fit_transform(X_train[['Gender']])
X_test_Gender = ohe_Gender.transform(X_test[['Gender']])
X_train_Gender

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], shape=(4000, 3))

In [14]:
X_test_Gender

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], shape=(1000, 3))

In [15]:
# Apply Ordinal Encoder to Grade since it is ordinal categorical value
oe_Grade = OrdinalEncoder(categories = [['High School','Undergraduate','Postgraduate']])
X_train_Grade = oe_Grade.fit_transform(X_train[['Grade']])
X_test_Grade = oe_Grade.fit_transform(X_test[['Grade']])
X_train_Grade

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [2.],
       [2.]], shape=(4000, 1))

In [16]:
X_test_Grade

array([[2.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [1.],
       [2.],
       [2.],

In [17]:
# Apply Label encoding for Result since it is output feature
le_Result = LabelEncoder()
y_train_Result = le_Result.fit_transform(y_train)
y_test_Result = le_Result.transform(y_test)
y_train_Result

array([0, 0, 2, ..., 2, 2, 2], shape=(4000,))

In [18]:
# Concatenate all values
X_train_new = np.concatenate(( X_train_Age, X_train_Gender, X_train_Grade), axis=1)
# also the test data
X_test_new = np.concatenate((X_test_Age, X_test_Gender, X_test_Grade), axis=1)

X_train_new.shape

(4000, 5)

In [20]:
# Implementation of model
clf = DecisionTreeClassifier()
clf.fit(X_train_new, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [22]:
# Prediction
y_pred = clf.predict(X_test_new)
y_pred

array(['Average', 'Average', 'Poor', 'Average', 'Good', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Good', 'Good', 'Poor',
       'Poor', 'Poor', 'Poor', 'Good', 'Good', 'Poor', 'Poor', 'Poor',
       'Average', 'Poor', 'Good', 'Good', 'Average', 'Good', 'Poor',
       'Good', 'Good', 'Poor', 'Poor', 'Average', 'Good', 'Average',
       'Average', 'Poor', 'Average', 'Good', 'Good', 'Poor', 'Average',
       'Good', 'Poor', 'Good', 'Good', 'Good', 'Poor', 'Good', 'Average',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Average', 'Poor', 'Average', 'Average',
       'Poor', 'Good', 'Good', 'Average', 'Poor', 'Good', 'Poor',
       'Average', 'Good', 'Poor', 'Good', 'Good', 'Average', 'Good',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Poor', 'Good', 'Poor', 'Average', 'Average',
       'Good', 'Poor', 'Average', 'Poor', 'Average', 'Average', 'Average',
  

In [24]:
#accuracy
accuracy_score(y_pred, y_test)

0.335

In [28]:
# Code for production
import pickle
pickle.dump(ohe_Gender,open('Machine Learning/ohe_Gender.pkl','wb'))
pickle.dump(oe_Grade,open('Machine Learning/oe_Grade.pkl','wb'))
pickle.dump(le_Result,open('Machine Learning/le_Result.pkl','wb'))
pickle.dump(clf,open('Machine Learning/clf.pkl','wb'))